# Aesterisk *Development* Compose file

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '54321:5432'
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5
#  neon-proxy:
#    image: ghcr.io/timowilhelm/local-neon-http-proxy:main
#    environment:
#      - PG_CONNECTION_STRING=postgresql://postgres:password@postgres:5432/postgres
#    ports:
#      - '54331:4444'
#    depends_on:
#      postgres:
#        condition: service_healthy
  neon:
    image: aesterisk-neon-proxy
    environment:
      - PG_CONNECTION_STRING=postgresql://postgres:password@postgres:5432/postgres
    ports:
      - '4445:4445'
    volumes:
      - ./docker/nginx/aesterisk.io.crt:/etc/neon/neon.pem
      - ./docker/nginx/aesterisk.io.key:/etc/neon/neon.key
    depends_on:
      postgres:
        condition: service_healthy
  web-proxy:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
      - '54331:4444'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/aesterisk.io.crt:/etc/ssl/certs/aesterisk.io.crt
      - ./docker/nginx/aesterisk.io.key:/etc/ssl/private/aesterisk.io.key
      # TODO: move /docker/nginx/aesterisk.io.{crt,key} to a clearer location, as well as adding a step in README.md so users know that a self-signed SSL record will be required for development
    depends_on:
#      neon-proxy:
#        condition: service_started
      neon:
        condition: service_started
